const TYPE_ORM_FIELD_NAME_AUTO_PK = 'AutoPK';
const TYPE_ORM_FIELD_NAME_CHARACTER_STRING = 'CharacterString';
const TYPE_ORM_FIELD_NAME_TEXT = 'Text';
const TYPE_ORM_FIELD_NAME_DECIMAL = 'Decimal';
const TYPE_ORM_FIELD_NAME_INTEGER = 'Integer';
const TYPE_ORM_FIELD_NAME_JSON = 'JSON';
const TYPE_ORM_FIELD_NAME_BOOLEAN = 'Boolean';
const TYPE_ORM_FIELD_NAME_FK = 'FK';

// ON DELETE options
const ON_DELETE_CASCADE = 'CASCADE';
const ON_DELETE_RESTRICT = 'RESTRICT';
const ON_DELETE_SET_NULL = 'SET NULL';
const ON_DELETE_NO_ACTION = 'NO ACTION';
const ON_DELETE_DO_NOTHING = 'DO_NOTHING';

// Default ON DELETE option
const ON_DELETE_DEFAULT = ON_DELETE_DO_NOTHING;

export {
    TYPE_ORM_FIELD_NAME_AUTO_PK,
    TYPE_ORM_FIELD_NAME_CHARACTER_STRING,
    TYPE_ORM_FIELD_NAME_TEXT,
    TYPE_ORM_FIELD_NAME_DECIMAL,
    TYPE_ORM_FIELD_NAME_INTEGER,
    TYPE_ORM_FIELD_NAME_JSON,
    TYPE_ORM_FIELD_NAME_BOOLEAN,
    TYPE_ORM_FIELD_NAME_FK,
    ON_DELETE_CASCADE,
    ON_DELETE_RESTRICT,
    ON_DELETE_SET_NULL,
    ON_DELETE_NO_ACTION,
    ON_DELETE_DO_NOTHING,
    ON_DELETE_DEFAULT,
};
