export const ApiErrorCode = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    PROFILE_ALREADY_EXISTS: 'PROFILE_ALREADY_EXISTS',
    INVALID_TOKEN: 'INVALID_TOKEN',
    PERMISSION_DENIED: 'PERMISSION_DENIED',
    NOT_FOUND: 'NOT_FOUND',
    CONFLICT: 'CONFLICT',
    BAD_REQUEST: 'BAD_REQUEST',
    INVALID_FIELD: 'INVALID_FIELD',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ApiErrorCodeKey = keyof typeof ApiErrorCode;
