const FILE_EXTENSION_TO_FORMAT_NAME = {
    json: 'JSON',
    csv: 'CSV',
    xlsx: 'XLSX',
    tsv: 'TSV',
    xml: 'XML',
    yaml: 'YAML',
    yml: 'YAML',
    pdf: 'PDF',
    txt: 'TXT',
    html: 'HTML',
    htm: 'HTML',
    md: 'MARKDOWN',
    markdown: 'MARKDOWN',
    jpeg: 'JPEG',
    jpg: 'JPEG',
    png: 'PNG',
    gif: 'GIF',
    webp: 'WEBP',
    svg: 'SVG',
    ico: 'ICO',
    bmp: 'BMP',
    mp4: 'MP4',
    mp3: 'MP3',
    wav: 'WAV',
    zip: 'ZIP',
    gz: 'GZIP',
    tar: 'TAR',
    xls: 'XLS',
    docx: 'DOCX',
    doc: 'DOC',
    pptx: 'PPTX',
    ppt: 'PPT',
} as const;

const MIME_TYPE_TO_FORMAT_NAME = {
    'application/json': 'JSON',
    'text/csv': 'CSV',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': 'XLSX',
    'text/tab-separated-values': 'TSV',
    'application/xml': 'XML',
    'text/xml': 'XML',
    'application/x-yaml': 'YAML',
    'text/yaml': 'YAML',
    'application/pdf': 'PDF',
    'text/plain': 'TXT',
    'text/html': 'HTML',
    'text/markdown': 'MARKDOWN',
    'image/jpeg': 'JPEG',
    'image/png': 'PNG',
    'image/gif': 'GIF',
    'image/webp': 'WEBP',
    'image/svg+xml': 'SVG',
    'image/x-icon': 'ICO',
    'image/vnd.microsoft.icon': 'ICO',
    'image/bmp': 'BMP',
    'video/mp4': 'MP4',
    'audio/mpeg': 'MP3',
    'audio/wav': 'WAV',
    'audio/x-wav': 'WAV',
    'application/zip': 'ZIP',
    'application/gzip': 'GZIP',
    'application/x-tar': 'TAR',
    'application/vnd.ms-excel': 'XLS',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document':
        'DOCX',
    'application/msword': 'DOC',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation':
        'PPTX',
    'application/vnd.ms-powerpoint': 'PPT',
    'application/octet-stream': 'OCTET_STREAM',
} as const;

export { FILE_EXTENSION_TO_FORMAT_NAME, MIME_TYPE_TO_FORMAT_NAME };
